### PR TITLE
COSYNE 2023 DANDI Search Tutorial

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Will post slides when closer to being finished as well

Notebook is courtesy of something Ben was putting together

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Commentable link for slides: https://docs.google.com/presentation/d/1OGwAxAHCHrpqamGqYcf2OBiRljxbIKhDszXNIJbgXDQ/edit?usp=sharing

**Review by oruebel — DISMISSED** [review]

**Comment by CodyCBakerPhD** [comment]
As per Ryans feedback, adding more images to cut back on and supplement the text/code

Also updating the advanced notebook to show how you can go beyond the DANDI API and pre-parsed metadata to scan all NWB files in a dandiset using streaming to parse some custom metadata field

**Comment by CodyCBakerPhD** [comment]
(Don't forget to squash on merge)

**Comment by rly** [comment]
I created a bit.ly link for the cosyne 2023 page: https://bit.ly/nwb-cosyne-2023
It would be nice to replace it in the slides if you have time - it would be easier for participants to type.

**Comment by CodyCBakerPhD** [comment]
@rly Link updated

**Review by rly — APPROVED** [review]

**Pull request merged**
