### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by bendichter** [comment]
this builds fine on my machine locally. I'm not sure what the problem is here.

**Comment by CodyCBakerPhD** [comment]
Looking into it, something about the docker image for the action no longer being available

**Comment by bendichter** [comment]
thanks for looking into this, @CodyCBakerPhD !

**Review by oruebel — APPROVED** [review]

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
@CodyCBakerPhD maybe I am missing something but does the preview page not work? Do I need to modify the URL in the preview comment above?

**Comment by CodyCBakerPhD** [comment]
@rly Can you try again - it takes a few minutes to deploy to the URL even after the workflow succeeds

**Comment by CodyCBakerPhD** [comment]
And yeah I guess the problems earlier really were just a service interruption

**Comment by bendichter** [comment]
I'm not surprised the favicon isn't working in the preview. The preview does some path manipulation stuff that makes it fragile to relative links, which might affect this. It's working locally and I think there's a good chance it will work in deployment

**Pull request merged**
