### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by deeptimittal12**

### CODE REVIEW

**Comment by bendichter** [comment]
Might be worthwhile to collaborate with @colehurwitz

**Comment by colehurwitz** [comment]
If you have some questions about SpikeInterface, I would be happy to help out if I can! As would @alejoe91 (although his time zone makes it difficult).

**Comment by deeptimittal12** [comment]
@bendichter Thanks for the idea :) @colehurwitz I can send you an email or we can arrange a skype call if possible. I am living in Heidelberg, Germany so the time zone should not be a problem.

**Comment by alejoe91** [comment]
Yep @deeptimittal12 let us know if you want to organize a call :)

**Comment by colehurwitz** [comment]
@deeptimittal12 @alejoe91 Sounds great! A skype call would be a good way to get the ball rolling.

**Pull request merged**
