### PR TITLE
nwb-jupyter-widgets_breakout

### PR DESCRIPTION
**Pull request by MRScheid**
Breakout session to demo new nwb jupyter widgets functionality.

### CODE REVIEW

**Comment by MRScheid** [comment]
@bendichter any other information I should add here?  Tried to be as comprehensive as possible with the breakout session description.

**Comment by rly** [comment]
@MRScheid is there any particular time that you would like to hold this breakout?

Best times that do not conflict with other sessions are:
Tue 2pm PDT
Wed 11pm
Wed 2pm
Thu 10pm
Thu 1pm

**Comment by MRScheid** [comment]
@rly I'm guessing you mean Thu 10am or 1pm?  I'm thinking that Thu 10am would be best.

**Comment by rly** [comment]
Yes, I meant Thu 10am. Great, I'll schedule that in. Let me know if you want to change it.

**Comment by rly** [comment]
I'll merge this now so that we have a page for this breakout session for the hackathon tomorrow, but please feel free to update this.

**Pull request merged**
